# Estatistica S5

### Limpeza e filtragem do dataset ccmec25a24

> Utilização das base dados_tratados.csv + ccmec50a69.csv e unificação das mesmas

- Limpeza unitaria dos dataset: dados_tratados.csv -> citopatologia_cariri.csv e ccmec50a69.csv -> mamografia_cariri.csv
- Unificação dos dataset após limpeza: citopatologia_cariri.csv + mamografia_cariri.csv = cito_e_mamo_cariri.csv

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set_theme(style="whitegrid")
import warnings
warnings.filterwarnings('ignore')

In [30]:
df = pd.read_csv("../../Datasets/N1/dados_tratados.csv")

In [31]:
cidades = [
    "Abaiara", "Altaneira", "Antonina do Norte", "Araripe", "Assaré",
    "Aurora", "Barbalha", "Barro", "Brejo Santo", "Campos Sales",
    "Caririaçu", "Crato", "Farias Brito", "Granjeiro", "Jardim",
    "Jati", "Juazeiro do Norte", "Mauriti", "Milagres", "Missão Velha",
    "Nova Olinda", "Penaforte", "Porteiras", "Potengi", "Salitre",
    "Santana do Cariri", "Tarrafas", "Várzea Alegre"
]

df_filtrado = df[
    (df['sg_uf'] == 'CE') & 
    (df['no_municipio'].isin(cidades)) 
#    (df['vl_indicador_calculado_mun'] == 0)
]

vl_indicador_calculado_mun
co_anomes
no_municipio
sg_uf
dt_atualizacao

In [32]:
df[
    (df['sg_uf'] == 'CE') & 
    (df['no_municipio'].isin(cidades))
#    (df['vl_indicador_calculado_mun'] == 0.0)
]

,co_anomes,co_ibge,vl_indicador_calculado_mun,co_uf,no_municipio,sg_uf,no_uf,co_regiao_brasil,no_regiao_brasil,sg_regiao_brasil,...,vl_indicador_calculado_ms,vl_indicador_calculado_uf,vl_indicador_calculado_reg,vl_indicador_calculado_br,vl_indicador_calculado_al,dt_competencia,dt_atualizacao,ds_unidade_medida,sg_granularidade,ds_granularidade
93,201612,230250,748.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
97,201612,230420,16742.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
101,201612,230730,4176.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
706,201712,230190,1.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,30560.0,204969.0,1614561.0,6844324.0,0.0,2017-12-01 12:00:00,2026-03-17 01:22:16,Número,MN,Município
708,201712,230250,4251.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,30560.0,204969.0,1614561.0,6844324.0,0.0,2017-12-01 12:00:00,2026-03-17 01:22:16,Número,MN,Município
712,201712,230420,19052.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,30560.0,204969.0,1614561.0,6844324.0,0.0,2017-12-01 12:00:00,2026-03-17 01:22:16,Número,MN,Município
716,201712,230730,4649.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,30560.0,204969.0,1614561.0,6844324.0,0.0,2017-12-01 12:00:00,2026-03-17 01:22:16,Número,MN,Município
1288,201812,230190,33.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,38364.0,245696.0,1743762.0,6956725.0,0.0,2018-12-01 12:00:00,2026-03-17 01:20:07,Número,MN,Município
1290,201812,230250,5414.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,38364.0,245696.0,1743762.0,6956725.0,0.0,2018-12-01 12:00:00,2026-03-17 01:20:07,Número,MN,Município
1294,201812,230420,13976.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,38364.0,245696.0,1743762.0,6956725.0,0.0,2018-12-01 12:00:00,2026-03-17 01:20:07,Número,MN,Município
1298,201812,230730,9735.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,38364.0,245696.0,1743762.0,6956725.0,0.0,2018-12-01 12:00:00,2026-03-17 01:20:07,Número,MN,Município
1861,201912,230250,6797.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,38959.0,230826.0,1688453.0,6805670.0,0.0,2019-12-01 12:00:00,2026-03-17 01:18:13,Número,MN,Município
1865,201912,230420,12545.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,38959.0,230826.0,1688453.0,6805670.0,0.0,2019-12-01 12:00:00,2026-03-17 01:18:13,Número,MN,Município
1869,201912,230730,11320.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,38959.0,230826.0,1688453.0,6805670.0,0.0,2019-12-01 12:00:00,2026-03-17 01:18:13,Número,MN,Município
2454,202012,230190,68.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,19836.0,144279.0,911743.0,3945483.0,0.0,2020-12-01 12:00:00,2026-03-17 01:16:29,Número,MN,Município
2456,202012,230250,4126.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,19836.0,144279.0,911743.0,3945483.0,0.0,2020-12-01 12:00:00,2026-03-17 01:16:29,Número,MN,Município
2459,202012,230420,8009.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,19836.0,144279.0,911743.0,3945483.0,0.0,2020-12-01 12:00:00,2026-03-17 01:16:29,Número,MN,Município
2462,202012,230730,4761.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,19836.0,144279.0,911743.0,3945483.0,0.0,2020-12-01 12:00:00,2026-03-17 01:16:29,Número,MN,Município
3029,202112,230190,54.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,28127.0,185316.0,1463149.0,6425019.0,0.0,2021-12-01 12:00:00,2026-03-17 01:14:49,Número,MN,Município
3031,202112,230250,5840.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,28127.0,185316.0,1463149.0,6425019.0,0.0,2021-12-01 12:00:00,2026-03-17 01:14:49,Número,MN,Município
3034,202112,230420,12935.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,28127.0,185316.0,1463149.0,6425019.0,0.0,2021-12-01 12:00:00,2026-03-17 01:14:49,Número,MN,Município
3037,202112,230730,6552.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,28127.0,185316.0,1463149.0,6425019.0,0.0,2021-12-01 12:00:00,2026-03-17 01:14:49,Número,MN,Município
3613,202212,230190,1.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,40702.0,277224.0,1846263.0,7116637.0,0.0,2022-12-01 12:00:00,2026-03-17 01:13:18,Número,MN,Município
3615,202212,230250,7732.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,40702.0,277224.0,1846263.0,7116637.0,0.0,2022-12-01 12:00:00,2026-03-17 01:13:18,Número,MN,Município
3618,202212,230420,20084.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,40702.0,277224.0,1846263.0,7116637.0,0.0,2022-12-01 12:00:00,2026-03-17 01:13:18,Número,MN,Município
3619,202212,230430,749.0,23,Farias Brito,CE,Ceará,2,Nordeste,NE,...,40702.0,277224.0,1846263.0,7116637.0,0.0,2022-12-01 12:00:00,2026-03-17 01:13:18,Número,MN,Município
3623,202212,230730,8579.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,40702.0,277224.0,1846263.0,7116637.0,0.0,2022-12-01 12:00:00,2026-03-17 01:13:18,Número,MN,Município
3626,202212,230840,163.0,23,Missão Velha,CE,Ceará,2,Nordeste,NE,...,40702.0,277224.0,1846263.0,7116637.0,0.0,2022-12-01 12:00:00,2026-03-17 01:13:18,Número,MN,Município
4237,202312,230250,8678.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,51208.0,322706.0,2007522.0,7915957.0,0.0,2023-12-01 12:00:00,2026-03-17 01:11:49,Número,MN,Município
4241,202312,230420,22309.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,51208.0,322706.0,2007522.0,7915957.0,0.0,2023-12-01 12:00:00,2026-03-17 01:11:49,Número,MN,Município
4246,202312,230730,11250.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,51208.0,322706.0,2007522.0,7915957.0,0.0,2023-12-01 12:00:00,2026-03-17 01:11:49,Número,MN,Município
4249,202312,230840,1425.0,23,Missão Velha,CE,Ceará,2,Nordeste,NE,...,51208.0,322706.0,2007522.0,7915957.0,0.0,2023-12-01 12:00:00,2026-03-17 01:11:49,Número,MN,Município
4846,202412,230190,2.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,39352.0,295805.0,1801231.0,7497110.0,0.0,2024-12-01 12:00:00,2026-03-17 01:10:33,Número,MN,Município
4848,202412,230250,6450.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,39352.0,295805.0,1801231.0,7497110.0,0.0,2024-12-01 12:00:00,2026-03-17 01:10:33,Número,MN,Município
4852,202412,230420,19756.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,39352.0,295805.0,1801231.0,7497110.0,0.0,2024-12-01 12:00:00,2026-03-17 01:10:33,Número,MN,Município
4857,202412,230730,8252.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,39352.0,295805.0,1801231.0,7497110.0,0.0,2024-12-01 12:00:00,2026-03-17 01:10:33,Número,MN,Município
4860,202412,230840,473.0,23,Missão Velha,CE,Ceará,2,Nordeste,NE,...,39352.0,295805.0,1801231.0,7497110.0,0.0,2024-12-01 12:00:00,2026-03-17 01:10:33,Número,MN,Município
5453,202512,230190,13.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
5455,202512,230250,7000.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
5459,202512,230420,19412.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
5464,202512,230730,10964.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
5467,202512,230840,1070.0,23,Missão Velha,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município

# Caso de dados inconsistentes

- Valores em 0.0 não tiveram envio de dados para o ano
- Em 2022 houve consolidação maior do uso do e-SUS APS 
- Submissão tardia de dados
- Perda de dados durante a migração
- Acumulo e dados para demais anos (Farias Brito 202212 - Compensando demais anos anteriores).
- Utilização de dois sistemas paralelos para registro de informações (SIAB e e-SUS APS) 
- SIAB passou a ser abolido em 2017 de forma obrigatoria 
- e-SUS APS implantado em 2013 e obigatório em 2017
- Em muitos municípios, o exame é coletado na UBS (APS) mas registrado no SISCAN
- Dados de cancer de colo de utero podem ter registrado em demais sitemas além do e-SUS APS, como o SISCAN.
- e-SUS registra apenas parte dos exames (profissionais), a partir disso o restante vai para SISCAN
- SISCAN e e-SUS são complementares e não se sobrepoem

In [33]:
df_filtrado.groupby('no_municipio').size().reset_index(name='quantidade')

        no_municipio  quantidade
0           Barbalha           7
1        Brejo Santo          10
2              Crato          10
3       Farias Brito           1
4  Juazeiro do Norte          10
5       Missão Velha           4

# Mamografia de 50 a 69 anos

In [34]:
df_mama = pd.read_csv("../../Datasets/N1/ccmec50a69.csv")

df_mama

,co_anomes,co_ibge,vl_indicador_calculado_mun,co_uf,no_municipio,sg_uf,no_uf,co_regiao_brasil,no_regiao_brasil,sg_regiao_brasil,...,vl_indicador_calculado_ms,vl_indicador_calculado_uf,vl_indicador_calculado_reg,vl_indicador_calculado_br,vl_indicador_calculado_al,dt_competencia,dt_atualizacao,ds_unidade_medida,sg_granularidade,ds_granularidade
0,202601,110001,0.0,11,Alta Floresta D'Oeste,RO,Rondônia,1,Norte,N,...,35,362,4377,205171,8372,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
1,202601,110002,107.0,11,Ariquemes,RO,Rondônia,1,Norte,N,...,327,362,4377,205171,8372,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
2,202601,110003,0.0,11,Cabixi,RO,Rondônia,1,Norte,N,...,35,362,4377,205171,8372,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
3,202601,110004,35.0,11,Cacoal,RO,Rondônia,1,Norte,N,...,35,362,4377,205171,8372,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
4,202601,110005,0.0,11,Cerejeiras,RO,Rondônia,1,Norte,N,...,35,362,4377,205171,8372,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61268,201612,522200,0.0,52,Vianópolis,GO,Goiás,5,Centro-Oeste,CO,...,8557,41689,72171,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
61269,201612,522205,0.0,52,Vicentinópolis,GO,Goiás,5,Centro-Oeste,CO,...,8557,41689,72171,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
61270,201612,522220,0.0,52,Vila Boa,GO,Goiás,5,Centro-Oeste,CO,...,924,41689,72171,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
61271,201612,522230,0.0,52,Vila Propício,GO,Goiás,5,Centro-Oeste,CO,...,6097,41689,72171,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
61272,201612,530010,819.0,53,Brasília,DF,Distrito Federal,5,Centro-Oeste,CO,...,819,819,72171,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município

In [35]:
df_cariri_mama = df_mama[
    (df_mama['sg_uf'] == 'CE') &
    (df_mama['no_municipio'].isin(cidades)) &
    (df_mama['vl_indicador_calculado_mun'] != 0)
]

df_filtrado_mama = df_cariri_mama.groupby('no_municipio').size().reset_index(name='quantidade')

df_filtrado_mama

df_cariri_mama

,co_anomes,co_ibge,vl_indicador_calculado_mun,co_uf,no_municipio,sg_uf,no_uf,co_regiao_brasil,no_regiao_brasil,sg_regiao_brasil,...,vl_indicador_calculado_ms,vl_indicador_calculado_uf,vl_indicador_calculado_reg,vl_indicador_calculado_br,vl_indicador_calculado_al,dt_competencia,dt_atualizacao,ds_unidade_medida,sg_granularidade,ds_granularidade
913,202601,230190,463.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,1339,7463,53040,205171,0,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
921,202601,230250,330.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,1339,7463,53040,205171,0,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
923,202601,230270,91.0,23,Campos Sales,CE,Ceará,2,Nordeste,NE,...,1339,7463,53040,205171,0,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
989,202601,230730,20.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,1339,7463,53040,205171,0,2026-01-01 12:00:00,2026-04-10 23:47:13,Número,MN,Município
9524,202512,230190,2064.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,15920,93616,715747,2880814,0,2025-12-01 12:00:00,2026-04-10 23:47:23,Número,MN,Município
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56616,201612,230190,2882.0,23,Barbalha,CE,Ceará,2,Nordeste,NE,...,9862,82283,698504,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
56624,201612,230250,1090.0,23,Brejo Santo,CE,Ceará,2,Nordeste,NE,...,9862,82283,698504,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
56644,201612,230420,1814.0,23,Crato,CE,Ceará,2,Nordeste,NE,...,9862,82283,698504,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
56692,201612,230730,1141.0,23,Juazeiro do Norte,CE,Ceará,2,Nordeste,NE,...,9862,82283,698504,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município
56776,201612,231400,253.0,23,Várzea Alegre,CE,Ceará,2,Nordeste,NE,...,9862,82283,698504,2778979,0,2016-12-01 12:00:00,2026-04-10 23:49:03,Número,MN,Município

# Geração de datasets filtrados.

Os seguintes datasets tiveram: 
- Removidas linhas que continham valores 0.0 na coluna vl_indicador_calculado_mun.
- Mantidas apenas linhas que fazem parte da região do Cariri, no ceará.

As operações ocorreram nos datasets ccmec50a69.csv e ccmec25a64_main.csv, que correspondem respectivamente a dados de exames citopatológicos e exames de mamografia.

Seguintes colunas foram mantidas (origem):
- sg_uf
- no_municipio
- vl_indicador_calculado_mun
- co_anomes
- dt_atualizacao

Colunas renomeadas para: 
- estado
- municipio
- valor_indicador
- ano_mes
- data_atalizacao

As seguintes colunas foram adicionadas:

- tipo_exame: informa o tipo de exame realizado (mamografia/citopatologia)

In [36]:
colunas = ['sg_uf', 'no_municipio', 'vl_indicador_calculado_mun', 'co_anomes', 'dt_atualizacao']

mapa_nomes = {
    'sg_uf': 'estado',
    'no_municipio': 'municipio',
    'vl_indicador_calculado_mun': 'valor_indicador',
    'co_anomes': 'ano_mes',
    'dt_atualizacao': 'data_atualizacao'
}

df_citopatologia_cariri = df_filtrado[colunas].rename(columns=mapa_nomes)
df_mamografia_cariri = df_cariri_mama[colunas].rename(columns=mapa_nomes)

df_citopatologia_cariri['tipo_exame'] = 'Citopatologico'
df_mamografia_cariri['tipo_exame'] = 'Mamografia'

df_citopatologia_cariri.to_csv("../../Datasets/N1/citopatologia_cariri.csv", index=False)
df_mamografia_cariri.to_csv("../../Datasets/N1/mamografia_cariri.csv", index=False)

### Criado novo dataset

Juntando os dataframes df_citopatologia_cariri e df_mamografia_cariri, foi criado um novo dataset chamado cito_e_mamo_cariri. <br>
Mantendo apenas os dados da região do cariri, descrevendo o tipo de exame realizado.

In [37]:
df_cito_e_mamo = pd.concat(
    [df_citopatologia_cariri, df_mamografia_cariri],
    ignore_index=True
)

df_cito_e_mamo = df_cito_e_mamo[df_cito_e_mamo['ano_mes'] != 202601]

df_cito_e_mamo.to_csv('../../Datasets/N1/cito_e_mamo_cariri.csv', index=False)