# Processamento de dados para novas análises
---
Novo processo sob datasets mamografia_atendbrCE e cito_colo_atendbrCE

Será gerado um novo dataset, que será o tratamento e a fusão dos dados em um só

In [37]:
# Imports

import pandas as pd
import seaborn as sns

In [38]:
# Carregando dados

# Cidades do cariri
cidades_cariri = [
    "ABAIARA", "ALTANEIRA", "ANTONINA DO NORTE", "ARARIPE", "ASSARE",
    "AURORA", "BARBALHA", "BARRO", "BREJO SANTO", "CAMPOS SALES",
    "CARIRIACU", "CRATO", "FARIAS BRITO", "GRANJEIRO", "JARDIM",
    "JATI", "JUAZEIRO DO NORTE", "MAURITI", "MILAGRES", "MISSAO VELHA",
    "NOVA OLINDA", "PENAFORTE", "PORTEIRAS", "POTENGI", "SALITRE",
    "SANTANA DO CARIRI", "TARRAFAS", "VARZEA ALEGRE"
]

# Datasets
df_cito_siscan = pd.read_csv("../../Datasets/N1/cito_colo_atendbrCE.csv", delimiter=";") 
df_mamo_siscan = pd.read_csv("../../Datasets/N1/mamografia_atendbrCE.csv", delimiter=";")

In [39]:
df_cito_siscan

,municipio_de_saude,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Total
0,230010 ABAIARA,0,1204,798,972,389,498,728,910,880,727,7106
1,230015 ACARAPE,1,537,288,541,324,375,522,713,568,528,4397
2,230020 ACARAU,263,3342,3539,3152,2732,2077,2774,3348,4985,3294,29506
3,230030 ACOPIARA,568,286,2806,2416,886,1756,1900,2603,1951,2348,17520
4,230040 AIUABA,111,728,860,771,717,369,735,631,695,1006,6623
...,...,...,...,...,...,...,...,...,...,...,...,...
179,231390 URUOCA,87,452,353,666,362,494,574,1421,797,732,5938
180,231395 VARJOTA,59,712,827,726,359,1540,1465,1424,1254,1508,9874
181,231400 VARZEA ALEGRE,79,2778,3152,2447,2074,751,287,487,157,0,12212
182,231410 VICOSA DO CEARA,394,2831,3147,3599,2008,2794,2802,4242,3195,3282,28294
183,Total,54083,279170,333603,329150,197582,259780,319121,394076,364706,355369,2886640

In [40]:
df_mamo_siscan

,municipio_de_saude,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,total
0,230010 ABAIARA,0,117,106,217,118,352,117,237,188,187,1639
1,230015 ACARAPE,1,163,0,168,1,0,172,242,179,171,1097
2,230020 ACARAU,476,3,938,305,0,0,1422,1230,1259,1245,6878
3,230030 ACOPIARA,0,167,617,1052,567,655,815,1025,554,973,6425
4,230040 AIUABA,0,1,160,2,0,0,0,181,219,267,830
...,...,...,...,...,...,...,...,...,...,...,...,...
180,231390 URUOCA,1,2,10,64,23,222,101,215,178,4,820
181,231395 VARJOTA,1,171,235,368,316,92,241,257,39,230,1950
182,231400 VARZEA ALEGRE,120,677,465,1,0,356,368,602,809,1372,4770
183,231410 VICOSA DO CEARA,41,86,570,555,183,707,819,970,852,988,5771
184,Total,36636,76952,86442,97768,70521,100821,111136,131335,132174,154609,998394

# Formatando Datasets

---

Os dados apresentados não estão em um formato aceitável para análise.

Foi feito:

- remoção do código de municipio e inseri-lo em uma coluna separada

In [41]:

try:
    # Drop da coluna municipio/codigo original
    mun_col_cito = df_cito_siscan.pop('municipio_de_saude')
    mun_col_mamo = df_mamo_siscan.pop('municipio_de_saude')

    # Separacao de codigo e muicipio
    df_cito_siscan[['codigo_mun', 'municipio']] = mun_col_cito.str.extract(r'(\d+)\s+(.+?)\s*$')
    df_mamo_siscan[['codigo_mun', 'municipio']] = mun_col_mamo.str.extract(r'(\d+)\s+(.+?)\s*$')

except KeyError:
    print('Col municipio_de_saude já removido')

finally:
    print(df_cito_siscan.head())
    print(df_mamo_siscan.head())

   2016  2017  2018  2019  2020  2021  2022  2023  2024  2025   Total  \
0     0  1204   798   972   389   498   728   910   880   727    7106
1     1   537   288   541   324   375   522   713   568   528    4397
2   263  3342  3539  3152  2732  2077  2774  3348  4985  3294   29506
3   568   286  2806  2416   886  1756  1900  2603  1951  2348   17520
4   111   728   860   771   717   369   735   631   695  1006    6623

  codigo_mun municipio
0     230010   ABAIARA
1     230015   ACARAPE
2     230020    ACARAU
3     230030  ACOPIARA
4     230040    AIUABA
   2016  2017  2018  2019  2020  2021  2022  2023  2024  2025  total  \
0     0   117   106   217   118   352   117   237   188   187   1639
1     1   163     0   168     1     0   172   242   179   171   1097
2   476     3   938   305     0     0  1422  1230  1259  1245   6878
3     0   167   617  1052   567   655   815  1025   554   973   6425
4     0     1   160     2     0     0     0   181   219   267    830

  codigo_mun municipio
0     230010   ABAIARA
1     230015   ACARAPE
2     230020    ACARAU
3     230030  ACOPIARA
4     230040    AIUABA

In [42]:
df_citopatologia_cariri  = df_cito_siscan[
    (df_cito_siscan['municipio'].isin(cidades_cariri)) 
]
df_mamografia_cariri  = df_mamo_siscan[
    (df_mamo_siscan['municipio'].isin(cidades_cariri)) 
]

In [43]:
df_citopatologia_cariri

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Total,codigo_mun,municipio
0,0,1204,798,972,389,498,728,910,880,727,7106,230010,ABAIARA
6,33,538,420,402,217,45,0,0,0,0,1655,230060,ALTANEIRA
9,17,122,270,208,99,285,399,601,447,449,2897,230080,ANTONINA DO NORTE
15,34,1493,223,6,0,898,1654,1617,1242,1755,8922,230130,ARARIPE
18,1,1109,933,777,521,993,1676,1403,1583,1643,10639,230160,ASSARE
19,0,1841,1839,1834,941,812,1162,1403,1064,1284,12180,230170,AURORA
22,83,3020,3151,3006,1855,2942,2706,3245,3494,3132,26634,230190,BARBALHA
24,0,1424,900,771,444,638,579,1529,1218,1305,8808,230200,BARRO
30,194,2019,1617,2479,1707,2264,2790,3714,2413,3148,22345,230250,BREJO SANTO
32,2,854,737,777,425,763,1461,1319,1050,1350,8738,230270,CAMPOS SALES
37,7,1402,1047,1650,521,1148,1075,1956,2164,2079,13049,230320,CARIRIACU
50,116,3661,3523,3672,2588,4530,4694,7686,6401,5616,42487,230420,CRATO
56,108,1445,1196,1262,808,727,1819,1770,1475,1625,12235,230430,FARIAS BRITO
64,1,355,255,360,151,334,322,486,308,344,2916,230480,GRANJEIRO
95,91,1081,1851,1573,680,663,1127,1913,1009,1323,11311,230710,JARDIM
96,11,406,323,202,55,0,0,25,0,0,1022,230720,JATI
98,0,5445,9022,10763,4492,7086,9033,10701,8182,9331,74055,230730,JUAZEIRO DO NORTE
107,70,2018,1770,1493,825,1741,2441,3539,2843,2257,18997,230810,MAURITI
109,7,1644,1597,1454,731,1655,2165,1706,1524,1337,13820,230830,MILAGRES
112,2,874,0,270,463,813,1558,2009,1435,1312,8736,230840,MISSAO VELHA
120,19,576,469,549,235,508,500,735,574,548,4713,230920,NOVA OLINDA
136,0,566,333,273,127,231,431,214,0,0,2175,231060,PENAFORTE
143,84,1181,1380,1169,953,1138,1306,1458,1147,1758,11574,231110,PORTEIRAS
144,0,727,872,547,469,797,682,454,1214,1148,6910,231120,POTENGI
155,16,1076,787,970,486,1555,1113,1088,744,1090,8925,231195,SALITRE
157,0,620,328,711,381,618,1050,1014,736,805,6263,231210,SANTANA DO CARIRI
169,9,424,298,141,82,167,100,513,286,335,2355,231325,TARRAFAS
181,79,2778,3152,2447,2074,751,287,487,157,0,12212,231400,VARZEA ALEGRE

In [44]:
df_mamografia_cariri

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,total,codigo_mun,municipio
0,0,117,106,217,118,352,117,237,188,187,1639,230010,ABAIARA
6,0,41,19,6,1,0,91,152,216,64,590,230060,ALTANEIRA
9,0,146,6,2,0,128,90,281,154,265,1072,230080,ANTONINA DO NORTE
15,0,216,27,2,4,229,183,702,448,766,2577,230130,ARARIPE
18,30,238,118,45,51,50,119,395,543,513,2102,230160,ASSARE
19,6,99,300,381,78,184,346,388,316,667,2765,230170,AURORA
22,0,1747,2479,2115,1869,2333,1681,2314,2599,2057,19194,230190,BARBALHA
24,0,0,298,395,294,367,171,470,273,396,2664,230200,BARRO
30,5,17,86,923,877,1051,1075,1135,1299,1549,8017,230250,BREJO SANTO
32,0,158,0,0,0,658,227,1076,598,1008,3725,230270,CAMPOS SALES
37,0,5,36,297,179,138,123,366,267,336,1747,230320,CARIRIACU
50,948,2285,1233,2,2106,1929,2294,2927,3901,4725,22350,230420,CRATO
56,65,230,103,218,0,0,213,405,182,125,1541,230430,FARIAS BRITO
64,0,143,1,52,84,7,40,189,128,83,727,230480,GRANJEIRO
95,0,40,190,540,277,337,464,688,873,337,3746,230710,JARDIM
96,0,29,104,198,93,162,155,208,67,155,1171,230720,JATI
98,0,1468,3061,4738,2453,3022,4165,3590,5027,2377,29901,230730,JUAZEIRO DO NORTE
108,3,132,194,391,445,692,417,590,689,537,4090,230810,MAURITI
110,4,259,177,524,117,340,403,494,377,245,2940,230830,MILAGRES
113,0,0,215,310,279,122,550,13,73,129,1691,230840,MISSAO VELHA
121,32,148,204,0,0,0,181,230,196,60,1051,230920,NOVA OLINDA
137,0,40,77,170,74,133,104,181,77,149,1005,231060,PENAFORTE
144,7,49,147,315,146,228,225,305,367,410,2199,231110,PORTEIRAS
145,42,173,85,0,0,101,111,353,225,584,1674,231120,POTENGI
156,5,24,39,0,0,190,108,448,251,607,1672,231195,SALITRE
158,83,162,153,0,0,0,238,262,259,254,1411,231210,SANTANA DO CARIRI
170,10,64,23,3,0,0,82,128,86,49,445,231325,TARRAFAS
182,120,677,465,1,0,356,368,602,809,1372,4770,231400,VARZEA ALEGRE

# Reorganização dos dados

---
A partir daqui serão tratados dados inconsistentes e preparação para novos datasets

In [45]:
df_long_cito = df_citopatologia_cariri.melt(
    id_vars=['municipio'],
    value_vars=[str(ano) for ano in range(2016, 2025)],
    var_name='ano',
    value_name='valor_indicador'
)

df_long_mamo = df_mamografia_cariri.melt(
    id_vars=['municipio'],
    value_vars=[str(ano) for ano in range(2016, 2025)],
    var_name='ano',
    value_name='valor_indicador'
)

In [46]:
df_long_cito

             municipio   ano  valor_indicador
0              ABAIARA  2016                0
1            ALTANEIRA  2016               33
2    ANTONINA DO NORTE  2016               17
3              ARARIPE  2016               34
4               ASSARE  2016                1
..                 ...   ...              ...
247            POTENGI  2024             1214
248            SALITRE  2024              744
249  SANTANA DO CARIRI  2024              736
250           TARRAFAS  2024              286
251      VARZEA ALEGRE  2024              157

[252 rows x 3 columns]

In [47]:
df_long_cito['ano_mes'] = df_long_cito['ano'] + '12'
df_long_cito['estado'] = 'CE'
df_long_cito['tipo_exame'] = 'Citopatologico'

df_long_mamo['ano_mes'] = df_long_cito['ano'] + '12'
df_long_mamo['estado'] = 'CE'
df_long_mamo['tipo_exame'] = 'Mamografia'

In [48]:
df_long_cito

             municipio   ano  valor_indicador ano_mes estado      tipo_exame
0              ABAIARA  2016                0  201612     CE  Citopatologico
1            ALTANEIRA  2016               33  201612     CE  Citopatologico
2    ANTONINA DO NORTE  2016               17  201612     CE  Citopatologico
3              ARARIPE  2016               34  201612     CE  Citopatologico
4               ASSARE  2016                1  201612     CE  Citopatologico
..                 ...   ...              ...     ...    ...             ...
247            POTENGI  2024             1214  202412     CE  Citopatologico
248            SALITRE  2024              744  202412     CE  Citopatologico
249  SANTANA DO CARIRI  2024              736  202412     CE  Citopatologico
250           TARRAFAS  2024              286  202412     CE  Citopatologico
251      VARZEA ALEGRE  2024              157  202412     CE  Citopatologico

[252 rows x 6 columns]

# Limpeza final

---

A partir daqui, o dataset cito_e_mamo.csv será atualizado para poder fazer um merge aos datasets atuais.
Os Datasets atuais também precisam ter certas colunas removidas antes de serem salvos

In [49]:
colunas = ['estado', 'municipio', 'valor_indicador', 'ano_mes', 'tipo_exame']

df_cito = df_long_cito[colunas]
df_mamo = df_long_mamo[colunas]

In [50]:
# Carregando cito_e_mamo.csv
df_cito_e_mamo_sus = pd.read_csv('../../Datasets/N1/cito_e_mamo_cariri.csv')

import unicodedata
# Necessario 
def normalizar(txt):
    if pd.isna(txt):
        return txt
    txt = str(txt).strip().upper()
    txt = unicodedata.normalize('NFKD', txt)
    txt = ''.join(c for c in txt if not unicodedata.combining(c))
    return txt

df_cito_e_mamo_sus['municipio'] = df_cito_e_mamo_sus['municipio'].apply(normalizar)

try:
    df_cito_e_mamo_sus = df_cito_e_mamo_sus.drop(columns='data_atualizacao')
except KeyError:
    print('Col já removida')

In [51]:
df_cito_e_mamo_sus

    estado          municipio  valor_indicador  ano_mes      tipo_exame
0       CE        BREJO SANTO            748.0   201612  Citopatologico
1       CE              CRATO          16742.0   201612  Citopatologico
2       CE  JUAZEIRO DO NORTE           4176.0   201612  Citopatologico
3       CE           BARBALHA              1.0   201712  Citopatologico
4       CE        BREJO SANTO           4251.0   201712  Citopatologico
..     ...                ...              ...      ...             ...
109     CE           BARBALHA           2882.0   201612      Mamografia
110     CE        BREJO SANTO           1090.0   201612      Mamografia
111     CE              CRATO           1814.0   201612      Mamografia
112     CE  JUAZEIRO DO NORTE           1141.0   201612      Mamografia
113     CE      VARZEA ALEGRE            253.0   201612      Mamografia

[114 rows x 5 columns]

# Merge de Datasets

---
Ocorretá agora o merge entre o dataset cito_e_mamo.csv, mamografia_atendbrCE.csv e cito_colo_atendbrCE.csv seguindo as regras abaixo:

- Linhas com valores anomes repetidas terão seus valores comparados, o valor com maior quantidade será substituido 
- Linhas com valores anomes não existentes em cito_e_mamo que estão presentes nos demais datasets serão adicionados

In [52]:
# Merge de mamografia_atendbrCE.csv e cito_colo_atendbrCE.csv

df_cito_e_mamo_siscan = pd.concat(
    [df_cito, df_mamo],
    ignore_index=True
)

df_cito_e_mamo_siscan = df_cito_e_mamo_siscan[df_cito_e_mamo_siscan['valor_indicador'] != 0]

df_cito_e_mamo_siscan['ano_mes'] = df_cito_e_mamo_siscan['ano_mes'].astype(int)

df_cito_e_mamo_siscan

    estado          municipio  valor_indicador  ano_mes      tipo_exame
1       CE          ALTANEIRA               33   201612  Citopatologico
2       CE  ANTONINA DO NORTE               17   201612  Citopatologico
3       CE            ARARIPE               34   201612  Citopatologico
4       CE             ASSARE                1   201612  Citopatologico
6       CE           BARBALHA               83   201612  Citopatologico
..     ...                ...              ...      ...             ...
499     CE            POTENGI              225   202412      Mamografia
500     CE            SALITRE              251   202412      Mamografia
501     CE  SANTANA DO CARIRI              259   202412      Mamografia
502     CE           TARRAFAS               86   202412      Mamografia
503     CE      VARZEA ALEGRE              809   202412      Mamografia

[452 rows x 5 columns]

In [53]:
# Concatecacao
df_concatenado_siscan_sus = pd.concat([
    df_cito_e_mamo_siscan, df_cito_e_mamo_sus
], ignore_index=True)


df_concatenado_siscan_sus

    estado          municipio  valor_indicador  ano_mes      tipo_exame
0       CE          ALTANEIRA             33.0   201612  Citopatologico
1       CE  ANTONINA DO NORTE             17.0   201612  Citopatologico
2       CE            ARARIPE             34.0   201612  Citopatologico
3       CE             ASSARE              1.0   201612  Citopatologico
4       CE           BARBALHA             83.0   201612  Citopatologico
..     ...                ...              ...      ...             ...
561     CE           BARBALHA           2882.0   201612      Mamografia
562     CE        BREJO SANTO           1090.0   201612      Mamografia
563     CE              CRATO           1814.0   201612      Mamografia
564     CE  JUAZEIRO DO NORTE           1141.0   201612      Mamografia
565     CE      VARZEA ALEGRE            253.0   201612      Mamografia

[566 rows x 5 columns]

In [54]:
# Agrupacao Final

df_final = (
    df_concatenado_siscan_sus
    .groupby(['estado', 'ano_mes', 'municipio', 'tipo_exame'], as_index=False)
    .agg({'valor_indicador': 'sum'})
)

In [55]:
df_final

    estado  ano_mes          municipio      tipo_exame  valor_indicador
0       CE   201612          ALTANEIRA  Citopatologico             33.0
1       CE   201612          ALTANEIRA      Mamografia            225.0
2       CE   201612  ANTONINA DO NORTE  Citopatologico             17.0
3       CE   201612            ARARIPE  Citopatologico             34.0
4       CE   201612             ASSARE  Citopatologico              1.0
..     ...      ...                ...             ...              ...
464     CE   202512              CRATO      Mamografia           3245.0
465     CE   202512  JUAZEIRO DO NORTE  Citopatologico          10964.0
466     CE   202512  JUAZEIRO DO NORTE      Mamografia            769.0
467     CE   202512       MISSAO VELHA  Citopatologico           1070.0
468     CE   202512      VARZEA ALEGRE      Mamografia            763.0

[469 rows x 5 columns]

# Salvamento dos Datasets

---
Os dados agora serão registrados em CSV.

In [56]:
df_final.to_csv('../../Datasets/N1/df_cito_e_mamo_sus_siscan.csv')
df_cito_e_mamo_siscan.to_csv('../../Datasets/N1/cito_e_mamo_siscan.csv')
df_cito.to_csv('../../Datasets/N1/cito_siscan.csv')
df_mamo.to_csv('../../Datasets/N1/mamo_siscan.csv')