# Estatistica S5

### Limpeza e filtragem do dataset ccmec25a24

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set_theme(style="whitegrid")
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("../../Datasets/dados_tratados.csv")

In [94]:
cidades = [
    "Abaiara", "Altaneira", "Antonina do Norte", "Araripe", "Assaré",
    "Aurora", "Barbalha", "Barro", "Brejo Santo", "Campos Sales",
    "Caririaçu", "Crato", "Farias Brito", "Granjeiro", "Jardim",
    "Jati", "Juazeiro do Norte", "Mauriti", "Milagres", "Missão Velha",
    "Nova Olinda", "Penaforte", "Porteiras", "Potengi", "Salitre",
    "Santana do Cariri", "Tarrafas", "Várzea Alegre"
]

df_filtrado = df[
    (df['sg_uf'] == 'CE') & 
    (df['no_municipio'].isin(cidades)) 
#    (df['vl_indicador_calculado_mun'] == 0)
]

In [98]:
df[
    (df['sg_uf'] == 'CE') & 
    (df['no_municipio'].isin(cidades))
#    (df['vl_indicador_calculado_mun'] == 0.0)
]

,co_anomes,co_ibge,vl_indicador_calculado_mun,co_uf,no_municipio,sg_uf,no_uf,co_regiao_brasil,no_regiao_brasil,sg_regiao_brasil,...,vl_indicador_calculado_ms,vl_indicador_calculado_uf,vl_indicador_calculado_reg,vl_indicador_calculado_br,vl_indicador_calculado_al,dt_competencia,dt_atualizacao,ds_unidade_medida,sg_granularidade,ds_granularidade
496,202512,230010,0.0,23,Abaiara,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
502,202512,230060,0.0,23,Altaneira,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
505,202512,230080,0.0,23,Antonina do Norte,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
511,202512,230130,0.0,23,Araripe,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
514,202512,230160,0.0,23,Assaré,CE,Ceará,2,Nordeste,NE,...,45145.0,293838.0,1766286.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51168,201612,231120,0.0,23,Potengi,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
51179,201612,231195,0.0,23,Salitre,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
51181,201612,231210,0.0,23,Santana do Cariri,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
51193,201612,231325,0.0,23,Tarrafas,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
51205,201612,231400,0.0,23,Várzea Alegre,CE,Ceará,2,Nordeste,NE,...,32353.0,242116.0,1624054.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município

In [95]:
df_filtrado.groupby('no_municipio').size().reset_index(name='quantidade')

         no_municipio  quantidade
0             Abaiara          10
1           Altaneira          10
2   Antonina do Norte          10
3             Araripe          10
4              Assaré          10
5              Aurora          10
6            Barbalha          10
7               Barro          10
8         Brejo Santo          10
9        Campos Sales          10
10          Caririaçu          10
11              Crato          10
12       Farias Brito          10
13          Granjeiro          10
14             Jardim          10
15               Jati          10
16  Juazeiro do Norte          10
17            Mauriti          10
18           Milagres          10
19       Missão Velha          10
20        Nova Olinda          10
21          Penaforte          10
22          Porteiras          10
23            Potengi          10
24            Salitre          10
25  Santana do Cariri          10
26           Tarrafas          10
27      Várzea Alegre          10