# Limpeza e organização do dataset
---
Com base nos feedbacks referentes ao working session, as seguintes mudanças serão feitas com base no dataset estudado anteriormente (**cito_e_mamo_sus_siscam.csv**).

1. Redução do escopo para exames de mamografia
2. Redução das cidades para apenas CRAJUBAR (Crato, Juazeiro e Barbalha)
3. Redução para apenas dados do SISCAN
4. Adição de granularização de etnia e idade

O dataset **mamo_siscan** já apresentam as dependências 1 e 3, portanto será utilizado ao invés de **cito_e_mamo_sus_siscam.csv**. <br>

Para as dependências 4, serão limpos respectivamente, **mamografia_siscan_etnia.csv** e **mamografia_siscan_faixa.csv** <br>

O processo terá como produto os arquivos chamados **mamografia_crajubar.csv**, **mamografia_etnia_crajubar.csv** e **mamografia_faixa_crajubar.csv** para análises mais precisas.

### Preparação de dados

In [8]:
import pandas as pd

In [9]:
df_mamo_siscan = pd.read_csv("../../Datasets/N1/mamo_siscan.csv")

df_mamo_siscan

,Unnamed: 0,estado,municipio,valor_indicador,ano_mes,tipo_exame
0,0,CE,ABAIARA,0,201612,Mamografia
1,1,CE,ALTANEIRA,0,201612,Mamografia
2,2,CE,ANTONINA DO NORTE,0,201612,Mamografia
3,3,CE,ARARIPE,0,201612,Mamografia
4,4,CE,ASSARE,30,201612,Mamografia
...,...,...,...,...,...,...
247,247,CE,POTENGI,225,202412,Mamografia
248,248,CE,SALITRE,251,202412,Mamografia
249,249,CE,SANTANA DO CARIRI,259,202412,Mamografia
250,250,CE,TARRAFAS,86,202412,Mamografia
251,251,CE,VARZEA ALEGRE,809,202412,Mamografia

In [10]:
df_mamo_etnia = pd.read_csv("../../Datasets/N1/mamo_siscan.csv")

### Processo de limpeza

In [11]:
df_crajubar_ma_sus_siscan = df_mamo_siscan[
    (
        (df_mamo_siscan["municipio"] == "CRATO") |
        (df_mamo_siscan["municipio"] == "JUAZEIRO DO NORTE") |
        (df_mamo_siscan["municipio"] == "BARBALHA")
    )
]

df_crajubar_ma_sus_siscan

,Unnamed: 0,estado,municipio,valor_indicador,ano_mes,tipo_exame
6,6,CE,BARBALHA,0,201612,Mamografia
11,11,CE,CRATO,948,201612,Mamografia
16,16,CE,JUAZEIRO DO NORTE,0,201612,Mamografia
34,34,CE,BARBALHA,1747,201712,Mamografia
39,39,CE,CRATO,2285,201712,Mamografia
44,44,CE,JUAZEIRO DO NORTE,1468,201712,Mamografia
62,62,CE,BARBALHA,2479,201812,Mamografia
67,67,CE,CRATO,1233,201812,Mamografia
72,72,CE,JUAZEIRO DO NORTE,3061,201812,Mamografia
90,90,CE,BARBALHA,2115,201912,Mamografia
95,95,CE,CRATO,2,201912,Mamografia
100,100,CE,JUAZEIRO DO NORTE,4738,201912,Mamografia
118,118,CE,BARBALHA,1869,202012,Mamografia
123,123,CE,CRATO,2106,202012,Mamografia
128,128,CE,JUAZEIRO DO NORTE,2453,202012,Mamografia
146,146,CE,BARBALHA,2333,202112,Mamografia
151,151,CE,CRATO,1929,202112,Mamografia
156,156,CE,JUAZEIRO DO NORTE,3022,202112,Mamografia
174,174,CE,BARBALHA,1681,202212,Mamografia
179,179,CE,CRATO,2294,202212,Mamografia
184,184,CE,JUAZEIRO DO NORTE,4165,202212,Mamografia
202,202,CE,BARBALHA,2314,202312,Mamografia
207,207,CE,CRATO,2927,202312,Mamografia
212,212,CE,JUAZEIRO DO NORTE,3590,202312,Mamografia
230,230,CE,BARBALHA,2599,202412,Mamografia
235,235,CE,CRATO,3901,202412,Mamografia
240,240,CE,JUAZEIRO DO NORTE,5027,202412,Mamografia