In [1]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
warnings.filterwarnings('ignore')

# Etnia
# Carrega os dados de mamografia por grupo étnico no município de Crajubar.
df_etnia = pd.read_csv('../../Datasets/N2/mamografia_etnia_crajubar.csv')

# Faixa etária
# Carrega os dados de mamografia por faixa etária.
df_faixa = pd.read_csv('../../Datasets/N2/mamografia_faixa_crajubar.csv')

# Visão geral
# Carrega a base consolidada para comparar o total geral com os recortes por etnia e idade.
df_geral = pd.read_csv('../../Datasets/N2/mamografia_crajubar.csv')

In [6]:
# Remove espaços em branco nos nomes dos campos para evitar divergências entre as bases.
# df_etnia.columns = df_etnia.columns.str.strip()
# df_faixa.columns = df_faixa.columns.str.strip()
df_geral.columns = df_geral.columns.str.strip()

# print(df_etnia.columns.tolist())
# print(df_faixa.columns.tolist())
print(df_geral.columns.tolist())

['Unnamed: 0.1', 'Unnamed: 0', 'estado', 'municipio', 'valor_indicador', 'ano_mes', 'tipo_exame']

In [14]:
df_geral.head(25)

,Unnamed: 0.1,Unnamed: 0,estado,municipio,valor_indicador,ano_mes,tipo_exame
0,6,6,CE,BARBALHA,0,201612,Mamografia
1,11,11,CE,CRATO,948,201612,Mamografia
2,16,16,CE,JUAZEIRO DO NORTE,0,201612,Mamografia
3,34,34,CE,BARBALHA,1747,201712,Mamografia
4,39,39,CE,CRATO,2285,201712,Mamografia
5,44,44,CE,JUAZEIRO DO NORTE,1468,201712,Mamografia
6,62,62,CE,BARBALHA,2479,201812,Mamografia
7,67,67,CE,CRATO,1233,201812,Mamografia
8,72,72,CE,JUAZEIRO DO NORTE,3061,201812,Mamografia
9,90,90,CE,BARBALHA,2115,201912,Mamografia
10,95,95,CE,CRATO,2,201912,Mamografia
11,100,100,CE,JUAZEIRO DO NORTE,4738,201912,Mamografia
12,118,118,CE,BARBALHA,1869,202012,Mamografia
13,123,123,CE,CRATO,2106,202012,Mamografia
14,128,128,CE,JUAZEIRO DO NORTE,2453,202012,Mamografia
15,146,146,CE,BARBALHA,2333,202112,Mamografia
16,151,151,CE,CRATO,1929,202112,Mamografia
17,156,156,CE,JUAZEIRO DO NORTE,3022,202112,Mamografia
18,174,174,CE,BARBALHA,1681,202212,Mamografia
19,179,179,CE,CRATO,2294,202212,Mamografia
20,184,184,CE,JUAZEIRO DO NORTE,4165,202212,Mamografia
21,202,202,CE,BARBALHA,2314,202312,Mamografia
22,207,207,CE,CRATO,2927,202312,Mamografia
23,212,212,CE,JUAZEIRO DO NORTE,3590,202312,Mamografia
24,230,230,CE,BARBALHA,2599,202412,Mamografia

In [16]:
df_geral[['municipio', 'valor_indicador', 'ano_mes']].head(10)

           municipio  valor_indicador  ano_mes
0           BARBALHA                0   201612
1              CRATO              948   201612
2  JUAZEIRO DO NORTE                0   201612
3           BARBALHA             1747   201712
4              CRATO             2285   201712
5  JUAZEIRO DO NORTE             1468   201712
6           BARBALHA             2479   201812
7              CRATO             1233   201812
8  JUAZEIRO DO NORTE             3061   201812
9           BARBALHA             2115   201912

In [17]:
df_geral['municipio'].unique()[:20]

<StringArray>
['BARBALHA', 'CRATO', 'JUAZEIRO DO NORTE']
Length: 3, dtype: str

In [11]:
df_geral['tipo_exame'].unique()

<StringArray>
['Mamografia']
Length: 1, dtype: str

In [12]:
df_geral['estado'].unique()

<StringArray>
['CE']
Length: 1, dtype: str

In [13]:
df_geral['municipio'].head(10)

0             BARBALHA
1                CRATO
2    JUAZEIRO DO NORTE
3             BARBALHA
4                CRATO
5    JUAZEIRO DO NORTE
6             BARBALHA
7                CRATO
8    JUAZEIRO DO NORTE
9             BARBALHA
Name: municipio, dtype: str

In [18]:
import pandas as pd
import requests
import plotly.express as px


# ================================
# Somar exames por município
# ================================

mapa_mamografia = (
    df_geral
    .groupby('municipio', as_index=False)
    ['valor_indicador']
    .sum()
)


# ================================
# Baixar GeoJSON dos municípios CE
# ================================

url = "https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-23-mun.json"

geo_ce = requests.get(url).json()


# ================================
# Criar mapa
# ================================

fig = px.choropleth_mapbox(
    mapa_mamografia,
    geojson=geo_ce,
    locations="municipio",
    featureidkey="properties.name",
    color="valor_indicador",
    color_continuous_scale="YlOrRd",
    hover_name="municipio",
    hover_data={
        "valor_indicador": ":,"
    },
    mapbox_style="carto-positron",
    center={
        "lat": -5.2,
        "lon": -39.5
    },
    zoom=6,
    opacity=0.75
)


fig.update_layout(
    title="Distribuição de mamografias realizadas por município - Ceará",
    height=800
)


fig.show(renderer="browser")