# Análise de dados sob Dataset
### Análise feita sob dataset ccmec25a64_original.csv

---
### Preparação de dados, Imports e ajustes iniciais

In [ ]:
# Imports
import pandas as pd
import numpy as np
import matplotlib as plt

In [11]:
# Carregando Dataset and variaveis necessarias
bronze_df = pd.read_csv('../data/bronze/ccmec25a64_main.csv')

### Códigos

As variáveis abaixo são todas Qualitativas Nominais, pois principalmente, classificam cada linha por seus códigos.
```
- co_ibge: Código IBGE do município.
- co_uf: Código da Unidade da Federação.
- co_regiao_saude: Código da região de saúde.
- co_macro: Código da macrorregião.
``` 


Quanto a essa variavel, co_anomes, é uma ordinal categorica, principalmente por ser uma combinação entre Ano + mês.
```
- co_anomes: Código no formato Ano + Mês (Ex.: 202301 => Janeiro de 2023)
```

In [19]:

codigos_nome = {
'co_ibge': 'Codigo_IBGE', 
 'co_uf': 'Codigo_unidade_federacao', 
 'co_regiao_saude': 'Codigo_Regiao_saude',
 'co_macro': 'Codigo_macrorregiao',
 'co_anomes': 'Codigo_Ano_Mes'}

bronze_df.rename(columns=codigos_nome)[['Codigo_IBGE', 'Codigo_unidade_federacao', 'Codigo_Regiao_saude', 'Codigo_macrorregiao', 'Codigo_Ano_Mes']]

,Codigo_IBGE,Codigo_unidade_federacao,Codigo_Regiao_saude,Codigo_macrorregiao,Codigo_Ano_Mes
0,412440,41,41008,4108,202512
1,412450,41,41015,4106,202512
2,412460,41,41014,4106,202512
3,412470,41,41018,4105,202512
4,412480,41,41007,4108,202512
...,...,...,...,...,...
55697,522200,52,52002,5210,201612
55698,522205,52,52002,5210,201612
55699,522220,52,52003,5207,201612
55700,522230,52,52018,5209,201612
55701,530010,53,53001,5302,201612

### Siglas (Estados, Regiões, etc)

Os dados abaixo são variaveis quantitativas nominais, pricipalmente devido a serem 
```
- sg_uf: Sigla do estado. (Qualitativa Nominal)
- sg_regiao_brasil: Sigla da região. (Qualitativa Nominal)
- sg_granularidade: Sigla do nível do dado (ex: "MN" para Município). (Qualitativa Nominal)
```

,co_anomes,co_ibge,vl_indicador_calculado_mun,co_uf,no_municipio,sg_uf,no_uf,co_regiao_brasil,no_regiao_brasil,sg_regiao_brasil,...,vl_indicador_calculado_ms,vl_indicador_calculado_uf,vl_indicador_calculado_reg,vl_indicador_calculado_br,vl_indicador_calculado_al,dt_competencia,dt_atualizacao,ds_unidade_medida,sg_granularidade,ds_granularidade
0,202512,412440,0.0,41,Santo Antônio do Sudoeste,PR,Paraná,4,Sul,S,...,126079.0,506911.0,1265634.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
1,202512,412450,0.0,41,Santo Inácio,PR,Paraná,4,Sul,S,...,75051.0,506911.0,1265634.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
2,202512,412460,0.0,41,São Carlos do Ivaí,PR,Paraná,4,Sul,S,...,75051.0,506911.0,1265634.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
3,202512,412470,0.0,41,São Jerônimo da Serra,PR,Paraná,4,Sul,S,...,65572.0,506911.0,1265634.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
4,202512,412480,0.0,41,São João,PR,Paraná,4,Sul,S,...,126079.0,506911.0,1265634.0,7292814.0,0.0,2025-12-01 12:00:00,2026-03-17 01:09:47,Número,MN,Município
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55697,201612,522200,0.0,52,Vianópolis,GO,Goiás,5,Centro-Oeste,CO,...,21594.0,137185.0,407392.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
55698,201612,522205,0.0,52,Vicentinópolis,GO,Goiás,5,Centro-Oeste,CO,...,21594.0,137185.0,407392.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
55699,201612,522220,0.0,52,Vila Boa,GO,Goiás,5,Centro-Oeste,CO,...,1005.0,137185.0,407392.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
55700,201612,522230,0.0,52,Vila Propício,GO,Goiás,5,Centro-Oeste,CO,...,19380.0,137185.0,407392.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município
55701,201612,530010,48932.0,53,Brasília,DF,Distrito Federal,5,Centro-Oeste,CO,...,48932.0,48932.0,407392.0,6944755.0,0.0,2016-12-01 12:00:00,2026-03-17 01:25:03,Número,MN,Município